apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    {{- include "common.labels" . | indent 4 }}
  name: mapbox-update-job
  namespace: {{ .Release.Namespace }}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - env:
                - name: TZ
                  value: Europe/Oslo
                - name: JAVA_OPTIONS
                  value: -server -Xmx{{ .Values.resources.xmx }} -Dspring.config.location=/etc/application-config/application.properties
                      -Dfile.encoding=UTF-8
                - name: GCP_PROJECT
                  value: {{ .Values.environmentValues.gcpProject }}
              envFrom:
                - secretRef:
                    name: ror-asag-secrets

              image: {{ .Values.image.identifier }}
              imagePullPolicy: IfNotPresent
              name: mapbox-update-job
              resources:
                limits:
                  cpu: {{ .Values.resources.cpuLimit }}
                  memory: {{ .Values.resources.memLimit }}
                requests:
                  cpu: {{ .Values.resources.cpuRequest }}
                  memory: {{ .Values.resources.memRequest }}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              securityContext:
                allowPrivilegeEscalation: false
                runAsNonRoot: true
                capabilities:
                  drop: [ "ALL" ]
                seccompProfile:
                  type: RuntimeDefault
              volumeMounts:
              - name: application-config
                mountPath: /etc/application-config
                readOnly: true
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          serviceAccountName: application
          schedulerName: default-scheduler
          securityContext:
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          terminationGracePeriodSeconds: 30
          volumes:
          - name: application-config
            configMap:
              name: {{ .Values.configMapMount.name }}
              defaultMode: 420
  schedule: '30 06 * ? *'
  successfulJobsHistoryLimit: 1
  suspend: {{ .Values.suspend }}