common:
  deployment:
    enabled: false
  cron:
    enabled: true
    schedule: '30 06 * ? *'
    restartPolicy: Never
    suspend: true

  ingress:
    enabled: false

  service:
    enabled: false

  app: asag
  shortname: asag
  team: ror
  container:
    envFrom:
     - secretRef:
         name: ror-asag-secrets
    forceReplicas: 1
    image: ${artifact.metadata.image}
    cpuLimit: 1
    memoryLimit: 3000
    memory: 1000
    cpu: 0.1
    probes:
      enabled: false
    prometheus:
      enabled: false

  configmap:
    data:
      JAVA_OPTIONS: -server -Xmx1500m -Dfile.encoding=UTF-8
      TZ: Europe/Oslo
      MAPBOX_DOWNLOAD_DIRECTORY: files/tmp/mapbox
    enabled: true
    toEnv: true

